version: '3'
services:
  frontend:
    build:
      context: ./frontend-solidarityconnect/frontend-solidarityconnect
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - solidarity-network

  backend:
    build:
      context: ./backend-solidarityconnect
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_USER: ${DB_USER:-rooter}
      DB_PASSWORD: ${DB_PASSWORD:-Local123!}
      DB_NAME: ${DB_NAME:-solidarityconnect}
    depends_on:
      - db
    networks:
      - solidarity-network
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-Local123!}
      MYSQL_DATABASE: ${DB_NAME:-solidarityconnect}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - solidarity-network

networks:
  solidarity-network:
    driver: bridge

volumes:
  db_data:
    driver: local