version: '3'

x-common-frontend-backend: &common-frontend-backend
  networks:
    - solidarity-network

frontend:
  build:
    context: ./frontend-solidarityconnect/frontend-solidarityconnect
    dockerfile: Dockerfile
  security_opt:
    - no-new-privileges=false  # Correction ici
  ports:
    - "8081:80"  # Port frontend accessible via http://localhost:8081
  depends_on:
    - backend
  <<: *common-frontend-backend

backend:
  build:
    context: ./backend-solidarityconnect
    dockerfile: Dockerfile
  ports:
    - "5000:5000"  # Port backend accessible via http://localhost:5000
  environment:
    DB_HOST: db
    DB_USER: rooter
    DB_PASSWORD: Local123!
    DB_NAME: solidarityconnect
  depends_on:
    - db
  entrypoint: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]
  <<: *common-frontend-backend

db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: Local123!
    MYSQL_DATABASE: solidarityconnect
  volumes:
    - db_data:/var/lib/mysql
  networks:
    - solidarity-network

networks:
  solidarity-network:
    driver: bridge

volumes:
  db_data:
    driver: local