version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-solidarityconnect
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=0
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - solidarity-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    restart: unless-stopped

  backend:
    build:
      context: ./backend-solidarityconnect
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=0
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: admin  # ✅ Changer "root" par "admin" pour éviter les conflits
      DB_PASSWORD: Local123!
      DB_NAME: SolidarityConnect_DB
      DB_PORT: 3306
      PORT: 5000
      JWT_SECRET: mon_secret_jwt
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["sh", "-c", "sleep 10 && npm start"]  # ✅ Attente plus longue pour s'assurer que MySQL est bien démarré
    networks:
      - solidarity-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "768M"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:5.7
    container_name: projetssoutenanceperso202510000codeurs_db_1
    environment:
      MYSQL_ROOT_PASSWORD: Local123!  # ✅ Conserver cette ligne
      MYSQL_DATABASE: SolidarityConnect_DB
      MYSQL_USER: admin  # ✅ Créer un utilisateur spécifique autre que root
      MYSQL_PASSWORD: Local123!
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # ✅ Changer le port sur l’hôte pour éviter les conflits
    networks:
      - solidarity-network
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "1G"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-pLocal123!"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

networks:
  solidarity-network:
    driver: bridge

volumes:
  db_data:
    driver: local
