version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-solidarityconnect/frontend-solidarityconnect
      dockerfile: Dockerfile
    ports:
      - "8081:80"  # Port frontend accessible via http://localhost:8081
    depends_on:
      - backend
    networks:
      - solidarity-network

  backend:
    build:
      context: ./backend-solidarityconnect
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Port backend accessible via http://localhost:5000
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]
    networks:
      - solidarity-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - solidarity-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  solidarity-network:
    driver: bridge

volumes:
  db_data:
    driver: local