version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-solidarityconnect/frontend-solidarityconnect
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - solidarity-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    restart: unless-stopped

  backend:
    build:
      context: ./backend-solidarityconnect
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Local123!
      DB_NAME: SolidarityConnect_DB
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["sh", "-c", "sleep 5 && npm start"]
    networks:
      - solidarity-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "768M"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:5.7
    container_name: projetssoutenanceperso202510000codeurs_db_1
    environment:
      MYSQL_ROOT_PASSWORD: Local123!
      MYSQL_DATABASE: SolidarityConnect_DB
      MYSQL_USER: root
      MYSQL_PASSWORD: Local123!
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - solidarity-network
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "1G"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

networks:
  solidarity-network:
    driver: bridge

volumes:
  db_data:
    driver: local
